name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build the site
        run: hugo

      - name: Add CNAME for Custom Domain
        run: echo "apptron.consulting" > public/CNAME  # Replace with your custom domain

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
