name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 compatibility

      # Set up Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3  # Updated to v3 for Node.js 20 compatibility
        with:
          hugo-version: 'latest'  # You can specify a version if needed

      # Build the site with Hugo
      - name: Build the site
        run: hugo

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to v4 for Node.js 20 compatibility
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
